config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :index, :create, :show, :update, :destroy] do
    resources :playlists, only: [:index, :show]
    # Virer l'index après tests
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:update, :edit]
    # Index ajouté par rapport au schema de DB
  resources :players, only: [:index, :new, :create, :update]
end

app/views/shared/_control-game-master.html.erb
<div class="master-control-area remote-controller" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.0)), url('<%= cl_image_path("AperoBlindTest/player-playing_dr5xkk", :crop => :fill) %>')">

  <div class="play">
<!--     <button class="mdc-icon-button">
      <i id="play" class="material-icons mdc-icon-button__icon">pause</i>
    </button> -->
    <span id="play" class="material-icons"> pause </span>
    <h3 id="play-label">PAUSE</h3>
  </div>

  <!-- <div class="middle-bar"></div> -->

  <div class="next">
<!--   <button class="mdc-icon-button">
    <i id="nexttrack" class="material-icons mdc-icon-button__icon">fast_forward</i>
  </button> -->
  <span id="nexttrack" class="material-icons"> fast_forward </span>
  <h3>NEXT</h3>
  </div>


  <div class="good-answer">
<!--     <button  class="mdc-icon-button">
      <i id="answer" class="material-icons mdc-icon-button__icon">done_outline</i>
    </button> -->
    <span id="answer" class="material-icons"> done </span>
  </div>

  <div class="endgame">
    <span id="end" class="material-icons" data-game-id="<%= @game.id %>"> stop </span>
    <h3> END GAME!</h3>
  </div>

<!--   <div class="logo-bottom-left" >

    <%#= cl_image_tag "AperoBlindTest/on-white-abt_hlwddy"%>
  </div> -->
</div>

app/views/shared/_counter-ten-seconds.html.erb
<div role="progressbar" class="mdc-linear-progress" aria-label="Example Progress Bar" aria-valuemin="0" aria-valuemax="1" aria-valuenow="0.5">
  <div class="mdc-linear-progress__buffer">
    <div class="mdc-linear-progress__buffer-bar"></div>
    <div class="mdc-linear-progress__buffer-dots"></div>
  </div>
  <div class="mdc-linear-progress__bar mdc-linear-progress__primary-bar">
    <span class="mdc-linear-progress__bar-inner"></span>
  </div>
  <div class="mdc-linear-progress__bar mdc-linear-progress__secondary-bar">
    <span class="mdc-linear-progress__bar-inner"></span>
  </div>
</div>

app/views/shared/_display_song.html.erb
<div id="display-song">

<!--     <span><h1>YOUR PLAYLIST:</h1></span> -->

  <span><h1 id="grey-background">" <%=@game.playlist.name.upcase%> "</h1></span>

  <span><h2>CURRENT TRACK</h2></span>
  <div class="cartouche">
<!--     <div class="track">
      <span><h2>TRACK</h2></span>
    </div> -->

    <div>
      <div class="cartouche-song">
        <span><h3>Title:</h3></span>
        <span><p><%=@game.current_track.title.upcase%></p></span>
      </div>

      <div class="cartouche-song">
        <h3>Artist:</h3>
        <p><%=@game.current_track.artist.upcase%></p>
      </div>
    </div>
  </div>

  <div class="pic-frame">
    <img src="<%=@game.current_track.image%>" class= "img-track" style="width:100%;height:100%;">
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_home.html.erb
# Show du gamemaster
<%= link_to "Create a new game", omniauth_authorize_path(:user, :spotify) %>


# Show du player
<%= simple_form_for :player, url: players_path, defaults: {label: false} do |f| %>
  <%= f.input :game_pin_entered %>
  <%= f.input :user_name %>
  <%= f.submit "Enter the Game!", class: "" %>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="shortcut icon" type="image/png" sizes="192x192"  href="<%= image_path 'icons/android-icon-192x192.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%#= image_tag "current_user.avatar" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_abt.html.erb
<div class="navbar-abt">
  <%= cl_image_tag("AperoBlindTest/white-bt_n9py56", crop: :fill, class: "blind-test") %>
  <%= cl_image_tag("AperoBlindTest/white-hp_jzffmp", crop: :fill, class: "blind-test") %>
</div>

app/views/shared/_navbar_abt_user.html.erb
<div class="navbar-abt">
  <%= cl_image_tag("AperoBlindTest/BT-blue_wuynsc", crop: :scale, class: "blind-test") %>
  <div><img src="<%= @game.user.avatar %>" class="avatar-large" alt=""></div>
</div>

app/views/shared/_player_management.html.erb
<div class="bottom hidden animate__animated" id="downhome">

  <%= simple_form_for :player, url: players_path, defaults: {label: false} do |f| %>
    <%= f.input :game_pin_entered, placeholder:'Game pin' %>



    <%= f.input :user_name, placeholder:'Username' %>
  <div class="submit-adjust">
    <%= f.submit "JOIN A GAME !", class: "btn btn-primary"%>
  </div>

  <% end %>


  <span class="material-icons" id="btn-back">
    <%= link_to "first_page", root_path  %>
  </span>
</div>

app/views/shared/_user_management.html.erb
<div class="top animate__animated">

  <p>
    <%= link_to "CREATE A GAME !", omniauth_authorize_path(:user, :spotify), class:"btn btn-primary blue-background" %>
  </p>

</div>