config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :index, :create, :show, :update, :destroy] do
    resources :playlists, only: [:index, :show]
    # Virer l'index après tests
    resources :answers, only: [:index, :new, :create]
  end
  resources :answers, only: [:update, :edit]
    # Index ajouté par rapport au schema de DB
  resources :players, only: [:index, :new, :create, :update]
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :tracks, dependent: :destroy
  belongs_to :user
  belongs_to :playlist
  belongs_to :current_track, class_name: 'Track', optional: true
  validates :user_id, :max_score, :state, :playlist_id, presence: true
  has_many :answers, through: :players

  def change_state
    #méthode pour modifier "state" d'une instance de game
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show]

  def index
    @games = Game.all
  end

  def show
    @answer = Answer.new
    @current_player = current_player if current_user == nil || current_user != @game.user
  end

  def new
    @game = Game.new
    @user_private_playlists = Playlist.where(user_id: current_user.id, searched: nil)
    @public_spotify_playlists = Playlist.where(user_id: nil)

    @searched_spotify_playlists = []
    if params[:query].present?
      @spotify_playlists = RSpotify::Playlist.search(params[:query], limit: 6)
      Playlist.where(user_id: current_user.id, searched: true).destroy_all
      @spotify_playlists.each do |playlist|
        pl = Playlist.create!(
              name: playlist.name,
              image: playlist.images.first["url"],
              spotify_id: playlist.id,
              user_id: current_user.id,
              searched: true,
            )
        @searched_spotify_playlists << pl
      end

    end
  end

  def create
    @game = Game.new(game_params_creation)
    @game.user = current_user
    # states = ["pending","paused","playing","ended"]
    @game.state = "pending"
    @game.game_pin = (('0'..'9').to_a + ('A'..'Z').to_a).sample(4).join
    @game.save!

    game_playlist_spotify_id = @game.playlist.spotify_id
    game_playlist = RSpotify::Playlist.find_by_id(game_playlist_spotify_id)

    game_playlist.tracks.each do |track|
      Track.create!(
        title: track.name,
        artist: track.artists.first.name,
        duration_ms: track.duration_ms,
        spotify_id: track.id,
        image: track.album.images.first["url"],
        game_id: @game.id
      )
    end

    @game.current_track = @game.tracks.first
    @game.save!

    redirect_to game_path(@game)
  end

  def update
    @game.update(game_params_update)
    @answer = Answer.new
    broadcast
  end

  def destroy
    @game.destroy
  end

  private

  def game_params_update
    params.require(:game).permit(:max_score, :playlist_id, :current_track_id, :state)
  end

  def game_params_creation
    params.require(:game).permit(:max_score, :playlist_id)
  end
  def set_game
    @game = Game.find(params[:id])
  end
end

app/views/games/_buzz_player.html.erb
 <div class="iphone-xs" style="background-image: linear-gradient(rgba(4,123,183,0.3),rgba(4,123,183,1)), url('<%= cl_image_path("AperoBlindTest/new-background_rxlqab", :fetch_format=>:auto, :crop => :scale) %>')">

  <%= render 'shared/navbar_abt' %>

  <div id="display-song-player">

    <span>
      <h1>
        <% @sorted = @game.players.sort_by { |obj| obj.score}.reverse %>
        <% @top3 = @game.players.sort_by { |obj| obj.score}.reverse.first(3) %>
        KEEP GOING!
      </h1>
    </span>

   <!--  <div>
      <h2>
        <%# if @current_player %>
        Your rank: <%#= @sorted.index(@current_player) + 1%> / <%#= @game.players.size %>
        <%# end %>
      </h2>
    </div> -->

    <span><h2>Top 3</h2></span>

    <div class="cartouche">
      <div>
          <% @top3.each do |player| %>
            <div class="cartouche-song">
              <h3><%= player.user_name %>:</h3><p><%= player.score %> POINTS </p>
            </div>
          <% end %>
      </div>
    </div>

    <div>
      <%# if @current_player == @game.answers.last.player %>
        <!-- <h4>YOUR TURN TO PLAY!</h4> -->
      <%# else %>
        <h4><%= @game.answers.last.player.user_name.upcase %> IS PLAYING</h4>
      <%# end %>
    </div>

  </div>

  <div class="display-gif-timer">
    <div id="countdown"></div>
  </div>

  <div id="modal-scores" class="hidden">
    <div class="container">
      <span class="close">&times;</span>
      <div class="score-recap">
        <h3 style="text-align: center"><strong>🏆 SCORE RECAP 🏆<strong></h3>
        <h4>
          <% @sorted = @game.players.sort_by { |obj| obj.score}.reverse %>
          <% @sorted.each do |player| %>
          <li><%= player.user_name %> : <%= player.score %></li>
          <% end %>
        </h4>
      </div>
    </div>
  </div>

</div>

app/views/games/_buzz_user.html.erb
<div class="iphone-xs" style="background-color: white">

  <%= render 'shared/navbar_abt_user' %>
  <%= render 'shared/display_song' %>
  <div id="buzz-user"></div>

  <div id="buzzer-area">
    <div class="playing">
      <span><h1 style="color: black; font-size: 28px"><%= @game.answers.last.player.user_name.upcase %></h1></span>
      <span><h1 style="color: #858585;font-size: 28px">IS PLAYING<h1></span>
    </div>

    <div id="buzzer-user">
      <div id="countdown" style="color: #030303"></div>
    </div>
  </div>

  <div class="master-control-area" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.0)), url('<%= cl_image_path("AperoBlindTest/media-player-v2_o5e3df", :width=> 357, :crop => :lpad) %>')">

    <div class="play">
  <!--     <button class="mdc-icon-button">
        <i id="play" class="material-icons mdc-icon-button__icon">pause</i>
      </button> -->
      <span id="resume" class="material-icons" style= "color: white" data-game-id="<%= @game.id %>"> close </span>
      <h3 style= "color: white"></h3>
    </div>

    <!-- <div class="middle-bar"></div> -->

    <div class="next">
  <!--   <button class="mdc-icon-button">
      <i id="nexttrack" class="material-icons mdc-icon-button__icon">fast_forward</i>
    </button> -->
    <span id="" class="material-icons" style="color: #c2c2c2;"> fast_forward </span>
    <h3 style="color: #c2c2c2;"></h3>
    </div>


    <div class="good-answer">
  <!--     <button  class="mdc-icon-button">
        <i id="answer" class="material-icons mdc-icon-button__icon">done_outline</i>
      </button> -->
      <h3 style="color: white;"></h3>
      <span id="validation" class="material-icons" style="color: white;" data-player-id="<%= @game.answers.last.player.id %>" data-game-id="<%= @game.id %>" > done </span>
    </div>

    <div class="endgame">
      <span id="end" class="material-icons" data-game-id="<%= @game.id %>"> stop </span>
      <h3> END GAME!</h3>
    </div>
</div>














<!-- buzz-user used to pause the game -->


<!-- <button type="button" class="btn btn-light" id="resume" data-game-id="<%= @game.id %>">Resume</button>
 -->




<!-- <button type="button" class="btn btn-success blue-background" id="validation" data-player-id="<%= @game.answers.last.player.id %>" data-game-id="<%= @game.id %>" > Validate <%= @game.answers.last.player.user_name %>'s answer </button> -->

app/views/games/_conditions_player.html.erb
<% if @game.state == "playing"%>
  <%= render 'games/playing_player' %>
<% elsif @game.state == "resuming"%>
  <%= render 'games/playing_player' %>
<% elsif @game.state == "buzz" %>
  <%= render 'games/buzz_player' %>
<% elsif @game.state == "pending" %>
  <%= render 'games/pending_player' %>
<% elsif @game.state == "ended" %>
  <%= render 'games/ended' %>
<% elsif @game.state == "validation" %>
  <%= render 'games/validation_player' %>
<% elsif @game.state == "waiting_for_next_song" %>
  <%= render 'games/waiting_for_next_song_player' %>
<% elsif @game.state == "ended" %>
  <%= render 'games/ended' %>
<% end %>

app/views/games/_conditions_user.html.erb
<% if @game.state != "pending" %>
  <div id="player" data-token-current-user="<%= @game.user.token %>"
  data-current-track-spotify-id="<%= @game.current_track.spotify_id %>"
  data-game-id="<%= @game.id %>"
  data-next-track-id="<%= @game.current_track_id + 1 %>"
  data-game-state="<%= @game.state %>"></div>
<% end %>

<% if @game.state == "playing"%>
  <%= render 'games/playing_user' %>
<% elsif @game.state == "resuming" %>
  <%= render 'games/playing_user' %>
<% elsif @game.state == "buzz" %>
  <%= render 'games/buzz_user' %>
<% elsif @game.state == "pending" %>
  <%= render 'games/pending_user' %>
<% elsif @game.state == "ended" %>
  <%= render 'games/ended' %>
<% elsif @game.state == "validation" %>
  <%= render 'games/validation_user' %>
<% elsif @game.state == "waiting_for_next_song" %>
  <%= render 'games/waiting_for_next_song_user' %>
<% elsif @game.state == "ended" %>
  <%= render 'games/ended' %>
<% end %>

app/views/games/_paused.html.erb
<% if current_user == @game.user %>
  # Show du gamemaster
  Image de la track en cours
  button title
  button title
  Bar de progression
  Buzzer name
  Buzzer countdown
  Start - pause (disabled) - next - stop

  <%= simple_form_for @game, method: "PATCH" do |f|%>
    <%= f.hidden_field :state, value:"playing", type:"hidden" %>
    <%= f.submit "Start again" %>
  <% end %>

<% elsif current_user.nil? || current_user != @game.user %>

  # Show des players
  <p>Buzzer (displayed) </p>
  <p>Mon score: <%= @current_player.score %></p>
  <p>Score en modal (pop up)</p>

<% end %>

app/views/games/_pending_player.html.erb
<div class="iphone-xs" style="background-image: linear-gradient(rgba(4,123,183,0.3),rgba(4,123,183,1)), url('<%= cl_image_path("AperoBlindTest/new-background_rxlqab", :fetch_format=>:auto, :crop => :scale) %>')">
  <%= render 'shared/navbar_abt' %>
  <div id="pending-player">
    <h1>GOOD LUCK!</h1>
    <span><h2>Gamemaster</h2></span>
    <div class="display-user-players">
      <img src="<%= @game.user.avatar %>" class="avatar-large" alt="">
      <h2 id="game-user">
      <%= @game.user.user_name %>  is waiting... Hurry up!
      </h2>
    </div>
    <span><h2>Players in the room</h2></span>
    <div class="cartouche">
      <div>
        <% sentences = ["is ready to play!", "is on fire!", "is going to win!"] %>
        <% @game.players.each do |player| %>
        <div class="cartouche-song">
          <h2 class="pendingplayers animate__animated"><%= player.user_name %> <%= sentences.sample %></h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/games/_pending_user.html.erb
<div class="iphone-xs" style="background-color: white">

<%= render 'shared/navbar_abt_user' %>

  <div id="pending-user">
    <h1>LET'S GO!</h1>

    <span><h2>Share this code with your friends</h2></span>
    <div class="box-game mt-3 mb-3">
      <span class="box-game-pin" style="font-family: 'Roboto Mono';"><%= @game.game_pin[0] %></span>
      <span class="box-game-pin" style="font-family: 'Roboto Mono';"><%= @game.game_pin[1] %></span>
      <span class="box-game-pin" style="font-family: 'Roboto Mono';"><%= @game.game_pin[2] %></span>
      <span class="box-game-pin" style="font-family: 'Roboto Mono';"><%= @game.game_pin[3] %></span>
    </div>

    <span><h2>Players in the room</h2></span>
    <div class="cartouche">
      <div>
        <div class="cartouche-song">
          <% sentences = ["is ready to play!", "is on fire!", "is going to win!"] %>
          <% @game.players.each do |player| %>
            <h2 class="pendingplayers animate__animated"><%= player.user_name %> <%= sentences.sample %></h2>
          <% end %>
        </div>
      </div>
    </div>

    <div class="box-launch-game mt-3 mb-3 submit-adjust">
      <%= simple_form_for @game, method: "PATCH" do |f|%>
      <%= f.hidden_field :state, value:"playing", type:"hidden" %>
      <%= f.submit " CLICK WHEN READY ! ", class:"btn btn-nicolas", style:"font-size: 20px;font-weight: 700;" %>
      <% end %>
    </div>
  </div>
</div>

app/views/games/_playing_player.html.erb
<div class="iphone-xs" style="background-image: linear-gradient(rgba(4,123,183,0.3),rgba(4,123,183,1)), url('<%= cl_image_path("AperoBlindTest/new-background_rxlqab", :fetch_format=>:auto, :crop => :scale) %>')">

  <%= render 'shared/navbar_abt' %>

  <div id="display-song-player" class="playing">

  <% @sorted = @game.players.sort_by { |obj| obj.score}.reverse %>
  <% @top3 = @game.players.sort_by { |obj| obj.score}.reverse.first(3) %>

    <span>
      <h1>
        KEEP GOING!
      </h1>
    </span>

    <!-- <div>
      <h2 class="ranking">
        <%# if @current_player %>
        Your rank: <%#= @sorted.index(@current_player) + 1%> / <%#= @game.players.size %>
        <%# end %>
      </h2>
    </div> -->

    <span><h2>Top 3</h2></span>

    <div class="cartouche">
      <div>
          <% @top3.each do |player| %>
            <div class="cartouche-song">
              <h3><%= player.user_name %>:</h3><p><%= player.score %> POINTS </p>
            </div>
          <% end %>
      </div>
    </div>

    <h4>BUZZ TO GUESS!</h4>

  </div>

  <div class="display-gif">
    <%= link_to game_answers_path(@game), method: :post do %>
      <%= cl_image_tag "AperoBlindTest/sound-1_luzly8.gif", crop: :fill, class:"gif-buzzer"%>
    <% end %>
  </div>

  <div id="modal-scores" class="hidden">
    <div class="container">
      <span class="close">&times;</span>
      <div class="score-recap">
        <h3 style="text-align: center"><strong>🏆 SCORE RECAP 🏆<strong></h3>
        <h4>
          <% @sorted = @game.players.sort_by { |obj| obj.score}.reverse %>
          <% @sorted.each do |player| %>
          <li><%= player.user_name %> : <%= player.score %></li>
          <% end %>
        </h4>
      </div>
    </div>
  </div>

</div>

app/views/games/_validation.html.erb
# Show du gamemaster
Image de la track en cours
Title et artist
button validation (artist + title)
Bar de progression
Buzzer name
Buzzer countdown
Start - pause (disabled) - next - stop

# Show du buzzer player
Buzzer (disabled)
Your answer in "countdown"

# Show des autres players
Buzzer (disabled)
The answer of buzzer.name in "countdown"

app/views/games/_validation_player.html.erb
# Show du buzzer player
Buzzer (disabled)
Your answer in "countdown"

# Show des autres players
Buzzer (disabled)
The answer of buzzer.name in "countdown"

app/views/games/_validation_user.html.erb
# Show du gamemaster
Image de la track en cours
Title et artist
button validation (artist + title)
Bar de progression
Buzzer name
Buzzer countdown
Start - pause (disabled) - next - stop

app/views/games/_waiting_for_next_song_user.html.erb
<div class="iphone-xs" style="background-image: linear-gradient(rgba(250,250,250,1),rgba(250,250,250,1)), url('<%= cl_image_path("AperoBlindTest/new-background_rxlqab", :fetch_format=>:auto, :crop => :scale) %>')">

  <%= render 'shared/navbar_abt_user' %>

  <div id="waiting-for-next-song" data-player-id="<%= @game.answers.last.player.id %>" data-game-id="<%= @game.id %>"></div>
  <% @sorted = @game.players.sort_by { |obj| obj.score}.reverse %>
  <% @top3 = @game.players.sort_by { |obj| obj.score}.reverse.first(3) %>

  <div id="display-song-player" style="color: #047BB7;">
    <h1 style="background-color: #047BB7; color: white"><strong>👏 GOOD JOB <%= @game.answers.last.player.user_name %> !</strong></h1>
    <h2 style="color:#047BB7;">Top 3</h2>
    <div class="cartouche" style="color:#047BB7;">
      <div>
        <% @top3.each_with_index do |player, index| %>
          <div class="cartouche-song">
              <h3 style="color:#047BB7;"><strong><%= index + 1 %>. <%= player.user_name %> :</strong> <%= player.score %> POINTS </h3>
          </div>
        <% end %>
      </div>
    </div>
    <h1 style="background-color: #047BB7; color: white"><strong>🐐 WTF <%= @sorted.last.user_name %>... SUCH A LOOSER</strong></h1>
    <h4 style="color: #047BB7">NEXT SONG IN...</h4>
  </div>

  <div class="display-gif-timer" style="border: 2px #047BB7 solid">
    <div id="timer-next-song" style="color: #047BB7"></div>
  </div>
</div>

app/views/games/new.html.erb
<div class="iphone-xs" style="background-image: linear-gradient(rgba(4,123,183,0.3),rgba(4,123,183,1)), url('<%= cl_image_path("AperoBlindTest/new-background_rxlqab", :fetch_format=>:auto, :crop => :scale) %>')">

<%= render 'shared/navbar_abt' %>

<div id="top-choose">
<!--   <div class="cartouche">
    <span class="material-icons"> library_music </span>
    <h2>Choose a playlist </h2>
  </div> -->

 <div class="search-bar">
    <div class="search-form-control form-group">
      <%= form_tag new_game_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search a playlist on Spotify..."
        %>
        <button name="button" type="Search" class="btn btn-ghost">
        <i class="fas fa-search"></i> Search </button>
      <% end %>
    </div>
</div>

  <%= simple_form_for @game, defaults: {label: false}, method: "POST" do |f| %>
    <div class="playlist-select pt-0 mt-0">

    <div class="cartouche sticky-top">
      <span class="material-icons" style="margin: 0px;"> arrow_drop_down</span>
      <span> <p style="color: white">scroll</p> </span>
    </div>
      <% if @searched_spotify_playlists.any? %>
        <p style="color: white; font-size: 16px;">RESULTS FOR '<%= params[:query].upcase %>'</p>
        <div class="category-choices mb-2">
          <% @searched_spotify_playlists.each do |playlist| %>
            <!-- <input type="hidden" value="" name="game[playlist_id]"> -->
            <input type="radio" class="hidden" value="<%= playlist.id %>" name="game[playlist_id]" style="display:none">
            <label for="playlist" class="category-choice">
              <img class="" src="<%= playlist.image %>" alt="">
              <p><%= playlist.name.first(20)%></p>
            </label>
          <% end %>
        </div>
      <% end %>

      <p style="color: white; font-size: 16px;">YOUR PLAYLISTS</p>
      <div class="category-choices mb-2">
        <% @user_private_playlists.each do |playlist| %>
          <input type="radio" class="hidden" value="<%= playlist.id %>" name="game[playlist_id]" style="display:none">
          <label for="playlist" class="category-choice">
            <img class="" src="<%= playlist.image %>" alt="">
            <p><%= playlist.name.first(20) %></p>
          </label>
        <% end %>
      </div>

      <% if @searched_spotify_playlists.blank? %>
      <p style="color: white; font-size: 16px;">RECOMMENDED PLAYLISTS</p>
      <div class="category-choices mb-2">
        <% @public_spotify_playlists.each do |playlist| %>
          <input type="radio" class="hidden" value="<%= playlist.id %>" name="game[playlist_id]" style="display:none">
          <label for="playlist" class="category-choice">
            <img class="" src="<%= playlist.image %>" alt="">
            <p><%= playlist.name.first(20) %></p>
          </label>
        <% end %>
      </div>
     <% end %>

  </div>
<div id= "bottom-choose">
<!--     <div class="cartouche">
      <span class="material-icons"> military_tech </span>
      <h2>Choose winning score</h2>
    </div> -->
        <div id="choose-bar" class="cartouche-bar">
          <h3>3pts</h3>
          <h3>20pts</h3>
          <h3>35pts</h3>
          <h3>50pts</h3>
    </div>

    <label for="game[max_score]"></label>

    <input type="range" name="game[max_score]" list="tickmarks" min="3" max="50" value="" step="15" class="range-bar">

    <datalist id="tickmarks">
      <option value="3">
      <option value="20">
      <option value="35">
      <option value="50">
    </datalist>

    <%= f.submit "  CREATE A NEW GAME !  ", class: "btn btn-light blue-background" %>
  <% end %>
  </div>
</div>

app/views/games/show.html.erb
<!-- Id game & data-game-id importants -->
<div id="game" data-game-id="<%= @game.id %>" data-user="<%= @game.user == current_user %>" data-player-id="<%= @current_player.id if @current_player%>">
  <% if current_user == @game.user %>
    <%= render 'games/conditions_user' %>
  <%# elsif current_user.nil? || current_user != @game.user %>
  <% else %>
    <%= render 'games/conditions_player' %>
  <% end %>
</div>